// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtobufData.proto

package mapper.control;

public final class ProtobufData {
  private ProtobufData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 mapperFieldConfigId = 1;
    /**
     * <code>optional int32 mapperFieldConfigId = 1;</code>
     */
    boolean hasMapperFieldConfigId();
    /**
     * <code>optional int32 mapperFieldConfigId = 1;</code>
     */
    int getMapperFieldConfigId();

    // optional string colName = 2;
    /**
     * <code>optional string colName = 2;</code>
     */
    boolean hasColName();
    /**
     * <code>optional string colName = 2;</code>
     */
    java.lang.String getColName();
    /**
     * <code>optional string colName = 2;</code>
     */
    com.google.protobuf.ByteString
        getColNameBytes();

    // optional string colType = 3;
    /**
     * <code>optional string colType = 3;</code>
     */
    boolean hasColType();
    /**
     * <code>optional string colType = 3;</code>
     */
    java.lang.String getColType();
    /**
     * <code>optional string colType = 3;</code>
     */
    com.google.protobuf.ByteString
        getColTypeBytes();

    // optional string colValue = 4;
    /**
     * <code>optional string colValue = 4;</code>
     */
    boolean hasColValue();
    /**
     * <code>optional string colValue = 4;</code>
     */
    java.lang.String getColValue();
    /**
     * <code>optional string colValue = 4;</code>
     */
    com.google.protobuf.ByteString
        getColValueBytes();

    // optional string action = 5;
    /**
     * <code>optional string action = 5;</code>
     */
    boolean hasAction();
    /**
     * <code>optional string action = 5;</code>
     */
    java.lang.String getAction();
    /**
     * <code>optional string action = 5;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();

    // optional string targetType = 6;
    /**
     * <code>optional string targetType = 6;</code>
     */
    boolean hasTargetType();
    /**
     * <code>optional string targetType = 6;</code>
     */
    java.lang.String getTargetType();
    /**
     * <code>optional string targetType = 6;</code>
     */
    com.google.protobuf.ByteString
        getTargetTypeBytes();

    // optional string targetName = 7;
    /**
     * <code>optional string targetName = 7;</code>
     */
    boolean hasTargetName();
    /**
     * <code>optional string targetName = 7;</code>
     */
    java.lang.String getTargetName();
    /**
     * <code>optional string targetName = 7;</code>
     */
    com.google.protobuf.ByteString
        getTargetNameBytes();

    // optional string targetObject = 8;
    /**
     * <code>optional string targetObject = 8;</code>
     */
    boolean hasTargetObject();
    /**
     * <code>optional string targetObject = 8;</code>
     */
    java.lang.String getTargetObject();
    /**
     * <code>optional string targetObject = 8;</code>
     */
    com.google.protobuf.ByteString
        getTargetObjectBytes();

    // optional string targetPk = 9;
    /**
     * <code>optional string targetPk = 9;</code>
     */
    boolean hasTargetPk();
    /**
     * <code>optional string targetPk = 9;</code>
     */
    java.lang.String getTargetPk();
    /**
     * <code>optional string targetPk = 9;</code>
     */
    com.google.protobuf.ByteString
        getTargetPkBytes();

    // optional string targetPkType = 10;
    /**
     * <code>optional string targetPkType = 10;</code>
     */
    boolean hasTargetPkType();
    /**
     * <code>optional string targetPkType = 10;</code>
     */
    java.lang.String getTargetPkType();
    /**
     * <code>optional string targetPkType = 10;</code>
     */
    com.google.protobuf.ByteString
        getTargetPkTypeBytes();

    // optional string time = 11;
    /**
     * <code>optional string time = 11;</code>
     */
    boolean hasTime();
    /**
     * <code>optional string time = 11;</code>
     */
    java.lang.String getTime();
    /**
     * <code>optional string time = 11;</code>
     */
    com.google.protobuf.ByteString
        getTimeBytes();

    // optional string mapperLogic = 12;
    /**
     * <code>optional string mapperLogic = 12;</code>
     */
    boolean hasMapperLogic();
    /**
     * <code>optional string mapperLogic = 12;</code>
     */
    java.lang.String getMapperLogic();
    /**
     * <code>optional string mapperLogic = 12;</code>
     */
    com.google.protobuf.ByteString
        getMapperLogicBytes();

    // optional string targetDbType = 13;
    /**
     * <code>optional string targetDbType = 13;</code>
     */
    boolean hasTargetDbType();
    /**
     * <code>optional string targetDbType = 13;</code>
     */
    java.lang.String getTargetDbType();
    /**
     * <code>optional string targetDbType = 13;</code>
     */
    com.google.protobuf.ByteString
        getTargetDbTypeBytes();
  }
  /**
   * Protobuf type {@code pkg.QData}
   */
  public static final class QData extends
      com.google.protobuf.GeneratedMessage
      implements QDataOrBuilder {
    // Use QData.newBuilder() to construct.
    private QData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QData defaultInstance;
    public static QData getDefaultInstance() {
      return defaultInstance;
    }

    public QData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              mapperFieldConfigId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              colName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              colType_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              colValue_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              action_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              targetType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              targetName_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              targetObject_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              targetPk_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              targetPkType_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              time_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              mapperLogic_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              targetDbType_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mapper.control.ProtobufData.internal_static_pkg_QData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mapper.control.ProtobufData.internal_static_pkg_QData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mapper.control.ProtobufData.QData.class, mapper.control.ProtobufData.QData.Builder.class);
    }

    public static com.google.protobuf.Parser<QData> PARSER =
        new com.google.protobuf.AbstractParser<QData>() {
      public QData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 mapperFieldConfigId = 1;
    public static final int MAPPERFIELDCONFIGID_FIELD_NUMBER = 1;
    private int mapperFieldConfigId_;
    /**
     * <code>optional int32 mapperFieldConfigId = 1;</code>
     */
    public boolean hasMapperFieldConfigId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 mapperFieldConfigId = 1;</code>
     */
    public int getMapperFieldConfigId() {
      return mapperFieldConfigId_;
    }

    // optional string colName = 2;
    public static final int COLNAME_FIELD_NUMBER = 2;
    private java.lang.Object colName_;
    /**
     * <code>optional string colName = 2;</code>
     */
    public boolean hasColName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string colName = 2;</code>
     */
    public java.lang.String getColName() {
      java.lang.Object ref = colName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          colName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string colName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getColNameBytes() {
      java.lang.Object ref = colName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string colType = 3;
    public static final int COLTYPE_FIELD_NUMBER = 3;
    private java.lang.Object colType_;
    /**
     * <code>optional string colType = 3;</code>
     */
    public boolean hasColType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string colType = 3;</code>
     */
    public java.lang.String getColType() {
      java.lang.Object ref = colType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          colType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string colType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getColTypeBytes() {
      java.lang.Object ref = colType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string colValue = 4;
    public static final int COLVALUE_FIELD_NUMBER = 4;
    private java.lang.Object colValue_;
    /**
     * <code>optional string colValue = 4;</code>
     */
    public boolean hasColValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string colValue = 4;</code>
     */
    public java.lang.String getColValue() {
      java.lang.Object ref = colValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          colValue_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string colValue = 4;</code>
     */
    public com.google.protobuf.ByteString
        getColValueBytes() {
      java.lang.Object ref = colValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string action = 5;
    public static final int ACTION_FIELD_NUMBER = 5;
    private java.lang.Object action_;
    /**
     * <code>optional string action = 5;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string action = 5;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          action_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string action = 5;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string targetType = 6;
    public static final int TARGETTYPE_FIELD_NUMBER = 6;
    private java.lang.Object targetType_;
    /**
     * <code>optional string targetType = 6;</code>
     */
    public boolean hasTargetType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string targetType = 6;</code>
     */
    public java.lang.String getTargetType() {
      java.lang.Object ref = targetType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTargetTypeBytes() {
      java.lang.Object ref = targetType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string targetName = 7;
    public static final int TARGETNAME_FIELD_NUMBER = 7;
    private java.lang.Object targetName_;
    /**
     * <code>optional string targetName = 7;</code>
     */
    public boolean hasTargetName() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string targetName = 7;</code>
     */
    public java.lang.String getTargetName() {
      java.lang.Object ref = targetName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTargetNameBytes() {
      java.lang.Object ref = targetName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string targetObject = 8;
    public static final int TARGETOBJECT_FIELD_NUMBER = 8;
    private java.lang.Object targetObject_;
    /**
     * <code>optional string targetObject = 8;</code>
     */
    public boolean hasTargetObject() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string targetObject = 8;</code>
     */
    public java.lang.String getTargetObject() {
      java.lang.Object ref = targetObject_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetObject_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetObject = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTargetObjectBytes() {
      java.lang.Object ref = targetObject_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetObject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string targetPk = 9;
    public static final int TARGETPK_FIELD_NUMBER = 9;
    private java.lang.Object targetPk_;
    /**
     * <code>optional string targetPk = 9;</code>
     */
    public boolean hasTargetPk() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string targetPk = 9;</code>
     */
    public java.lang.String getTargetPk() {
      java.lang.Object ref = targetPk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetPk_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetPk = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTargetPkBytes() {
      java.lang.Object ref = targetPk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetPk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string targetPkType = 10;
    public static final int TARGETPKTYPE_FIELD_NUMBER = 10;
    private java.lang.Object targetPkType_;
    /**
     * <code>optional string targetPkType = 10;</code>
     */
    public boolean hasTargetPkType() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string targetPkType = 10;</code>
     */
    public java.lang.String getTargetPkType() {
      java.lang.Object ref = targetPkType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetPkType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetPkType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getTargetPkTypeBytes() {
      java.lang.Object ref = targetPkType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetPkType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string time = 11;
    public static final int TIME_FIELD_NUMBER = 11;
    private java.lang.Object time_;
    /**
     * <code>optional string time = 11;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string time = 11;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          time_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string time = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string mapperLogic = 12;
    public static final int MAPPERLOGIC_FIELD_NUMBER = 12;
    private java.lang.Object mapperLogic_;
    /**
     * <code>optional string mapperLogic = 12;</code>
     */
    public boolean hasMapperLogic() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string mapperLogic = 12;</code>
     */
    public java.lang.String getMapperLogic() {
      java.lang.Object ref = mapperLogic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mapperLogic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mapperLogic = 12;</code>
     */
    public com.google.protobuf.ByteString
        getMapperLogicBytes() {
      java.lang.Object ref = mapperLogic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mapperLogic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string targetDbType = 13;
    public static final int TARGETDBTYPE_FIELD_NUMBER = 13;
    private java.lang.Object targetDbType_;
    /**
     * <code>optional string targetDbType = 13;</code>
     */
    public boolean hasTargetDbType() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string targetDbType = 13;</code>
     */
    public java.lang.String getTargetDbType() {
      java.lang.Object ref = targetDbType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetDbType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string targetDbType = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTargetDbTypeBytes() {
      java.lang.Object ref = targetDbType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDbType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      mapperFieldConfigId_ = 0;
      colName_ = "";
      colType_ = "";
      colValue_ = "";
      action_ = "";
      targetType_ = "";
      targetName_ = "";
      targetObject_ = "";
      targetPk_ = "";
      targetPkType_ = "";
      time_ = "";
      mapperLogic_ = "";
      targetDbType_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, mapperFieldConfigId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getColNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getColTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getColValueBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getActionBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTargetTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTargetNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getTargetObjectBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getTargetPkBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getTargetPkTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getTimeBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getMapperLogicBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getTargetDbTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mapperFieldConfigId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getColNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getColTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getColValueBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getActionBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTargetTypeBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTargetNameBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getTargetObjectBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getTargetPkBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTargetPkTypeBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getTimeBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getMapperLogicBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getTargetDbTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static mapper.control.ProtobufData.QData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mapper.control.ProtobufData.QData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mapper.control.ProtobufData.QData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mapper.control.ProtobufData.QData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mapper.control.ProtobufData.QData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mapper.control.ProtobufData.QData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mapper.control.ProtobufData.QData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mapper.control.ProtobufData.QData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mapper.control.ProtobufData.QData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mapper.control.ProtobufData.QData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mapper.control.ProtobufData.QData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pkg.QData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mapper.control.ProtobufData.QDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mapper.control.ProtobufData.internal_static_pkg_QData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mapper.control.ProtobufData.internal_static_pkg_QData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mapper.control.ProtobufData.QData.class, mapper.control.ProtobufData.QData.Builder.class);
      }

      // Construct using mapper.control.ProtobufData.QData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mapperFieldConfigId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        colName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        colType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        colValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        action_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        targetType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        targetName_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        targetObject_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        targetPk_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        targetPkType_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        mapperLogic_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        targetDbType_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mapper.control.ProtobufData.internal_static_pkg_QData_descriptor;
      }

      public mapper.control.ProtobufData.QData getDefaultInstanceForType() {
        return mapper.control.ProtobufData.QData.getDefaultInstance();
      }

      public mapper.control.ProtobufData.QData build() {
        mapper.control.ProtobufData.QData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mapper.control.ProtobufData.QData buildPartial() {
        mapper.control.ProtobufData.QData result = new mapper.control.ProtobufData.QData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mapperFieldConfigId_ = mapperFieldConfigId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.colName_ = colName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.colType_ = colType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.colValue_ = colValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.targetType_ = targetType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.targetName_ = targetName_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.targetObject_ = targetObject_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.targetPk_ = targetPk_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.targetPkType_ = targetPkType_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.mapperLogic_ = mapperLogic_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.targetDbType_ = targetDbType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mapper.control.ProtobufData.QData) {
          return mergeFrom((mapper.control.ProtobufData.QData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mapper.control.ProtobufData.QData other) {
        if (other == mapper.control.ProtobufData.QData.getDefaultInstance()) return this;
        if (other.hasMapperFieldConfigId()) {
          setMapperFieldConfigId(other.getMapperFieldConfigId());
        }
        if (other.hasColName()) {
          bitField0_ |= 0x00000002;
          colName_ = other.colName_;
          onChanged();
        }
        if (other.hasColType()) {
          bitField0_ |= 0x00000004;
          colType_ = other.colType_;
          onChanged();
        }
        if (other.hasColValue()) {
          bitField0_ |= 0x00000008;
          colValue_ = other.colValue_;
          onChanged();
        }
        if (other.hasAction()) {
          bitField0_ |= 0x00000010;
          action_ = other.action_;
          onChanged();
        }
        if (other.hasTargetType()) {
          bitField0_ |= 0x00000020;
          targetType_ = other.targetType_;
          onChanged();
        }
        if (other.hasTargetName()) {
          bitField0_ |= 0x00000040;
          targetName_ = other.targetName_;
          onChanged();
        }
        if (other.hasTargetObject()) {
          bitField0_ |= 0x00000080;
          targetObject_ = other.targetObject_;
          onChanged();
        }
        if (other.hasTargetPk()) {
          bitField0_ |= 0x00000100;
          targetPk_ = other.targetPk_;
          onChanged();
        }
        if (other.hasTargetPkType()) {
          bitField0_ |= 0x00000200;
          targetPkType_ = other.targetPkType_;
          onChanged();
        }
        if (other.hasTime()) {
          bitField0_ |= 0x00000400;
          time_ = other.time_;
          onChanged();
        }
        if (other.hasMapperLogic()) {
          bitField0_ |= 0x00000800;
          mapperLogic_ = other.mapperLogic_;
          onChanged();
        }
        if (other.hasTargetDbType()) {
          bitField0_ |= 0x00001000;
          targetDbType_ = other.targetDbType_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mapper.control.ProtobufData.QData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mapper.control.ProtobufData.QData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 mapperFieldConfigId = 1;
      private int mapperFieldConfigId_ ;
      /**
       * <code>optional int32 mapperFieldConfigId = 1;</code>
       */
      public boolean hasMapperFieldConfigId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 mapperFieldConfigId = 1;</code>
       */
      public int getMapperFieldConfigId() {
        return mapperFieldConfigId_;
      }
      /**
       * <code>optional int32 mapperFieldConfigId = 1;</code>
       */
      public Builder setMapperFieldConfigId(int value) {
        bitField0_ |= 0x00000001;
        mapperFieldConfigId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 mapperFieldConfigId = 1;</code>
       */
      public Builder clearMapperFieldConfigId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mapperFieldConfigId_ = 0;
        onChanged();
        return this;
      }

      // optional string colName = 2;
      private java.lang.Object colName_ = "";
      /**
       * <code>optional string colName = 2;</code>
       */
      public boolean hasColName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string colName = 2;</code>
       */
      public java.lang.String getColName() {
        java.lang.Object ref = colName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          colName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string colName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getColNameBytes() {
        java.lang.Object ref = colName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          colName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string colName = 2;</code>
       */
      public Builder setColName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        colName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string colName = 2;</code>
       */
      public Builder clearColName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        colName_ = getDefaultInstance().getColName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string colName = 2;</code>
       */
      public Builder setColNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        colName_ = value;
        onChanged();
        return this;
      }

      // optional string colType = 3;
      private java.lang.Object colType_ = "";
      /**
       * <code>optional string colType = 3;</code>
       */
      public boolean hasColType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string colType = 3;</code>
       */
      public java.lang.String getColType() {
        java.lang.Object ref = colType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          colType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string colType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getColTypeBytes() {
        java.lang.Object ref = colType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          colType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string colType = 3;</code>
       */
      public Builder setColType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        colType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string colType = 3;</code>
       */
      public Builder clearColType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        colType_ = getDefaultInstance().getColType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string colType = 3;</code>
       */
      public Builder setColTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        colType_ = value;
        onChanged();
        return this;
      }

      // optional string colValue = 4;
      private java.lang.Object colValue_ = "";
      /**
       * <code>optional string colValue = 4;</code>
       */
      public boolean hasColValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string colValue = 4;</code>
       */
      public java.lang.String getColValue() {
        java.lang.Object ref = colValue_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          colValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string colValue = 4;</code>
       */
      public com.google.protobuf.ByteString
          getColValueBytes() {
        java.lang.Object ref = colValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          colValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string colValue = 4;</code>
       */
      public Builder setColValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        colValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string colValue = 4;</code>
       */
      public Builder clearColValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        colValue_ = getDefaultInstance().getColValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string colValue = 4;</code>
       */
      public Builder setColValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        colValue_ = value;
        onChanged();
        return this;
      }

      // optional string action = 5;
      private java.lang.Object action_ = "";
      /**
       * <code>optional string action = 5;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string action = 5;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string action = 5;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string action = 5;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string action = 5;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000010);
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>optional string action = 5;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        action_ = value;
        onChanged();
        return this;
      }

      // optional string targetType = 6;
      private java.lang.Object targetType_ = "";
      /**
       * <code>optional string targetType = 6;</code>
       */
      public boolean hasTargetType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string targetType = 6;</code>
       */
      public java.lang.String getTargetType() {
        java.lang.Object ref = targetType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTargetTypeBytes() {
        java.lang.Object ref = targetType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetType = 6;</code>
       */
      public Builder setTargetType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        targetType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetType = 6;</code>
       */
      public Builder clearTargetType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        targetType_ = getDefaultInstance().getTargetType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetType = 6;</code>
       */
      public Builder setTargetTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        targetType_ = value;
        onChanged();
        return this;
      }

      // optional string targetName = 7;
      private java.lang.Object targetName_ = "";
      /**
       * <code>optional string targetName = 7;</code>
       */
      public boolean hasTargetName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string targetName = 7;</code>
       */
      public java.lang.String getTargetName() {
        java.lang.Object ref = targetName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTargetNameBytes() {
        java.lang.Object ref = targetName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetName = 7;</code>
       */
      public Builder setTargetName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        targetName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetName = 7;</code>
       */
      public Builder clearTargetName() {
        bitField0_ = (bitField0_ & ~0x00000040);
        targetName_ = getDefaultInstance().getTargetName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetName = 7;</code>
       */
      public Builder setTargetNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        targetName_ = value;
        onChanged();
        return this;
      }

      // optional string targetObject = 8;
      private java.lang.Object targetObject_ = "";
      /**
       * <code>optional string targetObject = 8;</code>
       */
      public boolean hasTargetObject() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string targetObject = 8;</code>
       */
      public java.lang.String getTargetObject() {
        java.lang.Object ref = targetObject_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetObject_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetObject = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTargetObjectBytes() {
        java.lang.Object ref = targetObject_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetObject_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetObject = 8;</code>
       */
      public Builder setTargetObject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        targetObject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetObject = 8;</code>
       */
      public Builder clearTargetObject() {
        bitField0_ = (bitField0_ & ~0x00000080);
        targetObject_ = getDefaultInstance().getTargetObject();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetObject = 8;</code>
       */
      public Builder setTargetObjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        targetObject_ = value;
        onChanged();
        return this;
      }

      // optional string targetPk = 9;
      private java.lang.Object targetPk_ = "";
      /**
       * <code>optional string targetPk = 9;</code>
       */
      public boolean hasTargetPk() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string targetPk = 9;</code>
       */
      public java.lang.String getTargetPk() {
        java.lang.Object ref = targetPk_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetPk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetPk = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTargetPkBytes() {
        java.lang.Object ref = targetPk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetPk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetPk = 9;</code>
       */
      public Builder setTargetPk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        targetPk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetPk = 9;</code>
       */
      public Builder clearTargetPk() {
        bitField0_ = (bitField0_ & ~0x00000100);
        targetPk_ = getDefaultInstance().getTargetPk();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetPk = 9;</code>
       */
      public Builder setTargetPkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        targetPk_ = value;
        onChanged();
        return this;
      }

      // optional string targetPkType = 10;
      private java.lang.Object targetPkType_ = "";
      /**
       * <code>optional string targetPkType = 10;</code>
       */
      public boolean hasTargetPkType() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string targetPkType = 10;</code>
       */
      public java.lang.String getTargetPkType() {
        java.lang.Object ref = targetPkType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetPkType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetPkType = 10;</code>
       */
      public com.google.protobuf.ByteString
          getTargetPkTypeBytes() {
        java.lang.Object ref = targetPkType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetPkType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetPkType = 10;</code>
       */
      public Builder setTargetPkType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        targetPkType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetPkType = 10;</code>
       */
      public Builder clearTargetPkType() {
        bitField0_ = (bitField0_ & ~0x00000200);
        targetPkType_ = getDefaultInstance().getTargetPkType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetPkType = 10;</code>
       */
      public Builder setTargetPkTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        targetPkType_ = value;
        onChanged();
        return this;
      }

      // optional string time = 11;
      private java.lang.Object time_ = "";
      /**
       * <code>optional string time = 11;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string time = 11;</code>
       */
      public java.lang.String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string time = 11;</code>
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        java.lang.Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string time = 11;</code>
       */
      public Builder setTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 11;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000400);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string time = 11;</code>
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        time_ = value;
        onChanged();
        return this;
      }

      // optional string mapperLogic = 12;
      private java.lang.Object mapperLogic_ = "";
      /**
       * <code>optional string mapperLogic = 12;</code>
       */
      public boolean hasMapperLogic() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string mapperLogic = 12;</code>
       */
      public java.lang.String getMapperLogic() {
        java.lang.Object ref = mapperLogic_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mapperLogic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mapperLogic = 12;</code>
       */
      public com.google.protobuf.ByteString
          getMapperLogicBytes() {
        java.lang.Object ref = mapperLogic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mapperLogic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mapperLogic = 12;</code>
       */
      public Builder setMapperLogic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        mapperLogic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mapperLogic = 12;</code>
       */
      public Builder clearMapperLogic() {
        bitField0_ = (bitField0_ & ~0x00000800);
        mapperLogic_ = getDefaultInstance().getMapperLogic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mapperLogic = 12;</code>
       */
      public Builder setMapperLogicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        mapperLogic_ = value;
        onChanged();
        return this;
      }

      // optional string targetDbType = 13;
      private java.lang.Object targetDbType_ = "";
      /**
       * <code>optional string targetDbType = 13;</code>
       */
      public boolean hasTargetDbType() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string targetDbType = 13;</code>
       */
      public java.lang.String getTargetDbType() {
        java.lang.Object ref = targetDbType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          targetDbType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string targetDbType = 13;</code>
       */
      public com.google.protobuf.ByteString
          getTargetDbTypeBytes() {
        java.lang.Object ref = targetDbType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetDbType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string targetDbType = 13;</code>
       */
      public Builder setTargetDbType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        targetDbType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetDbType = 13;</code>
       */
      public Builder clearTargetDbType() {
        bitField0_ = (bitField0_ & ~0x00001000);
        targetDbType_ = getDefaultInstance().getTargetDbType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string targetDbType = 13;</code>
       */
      public Builder setTargetDbTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        targetDbType_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pkg.QData)
    }

    static {
      defaultInstance = new QData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pkg.QData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pkg_QData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pkg_QData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtobufData.proto\022\003pkg\"\207\002\n\005QData\022\033\n\023m" +
      "apperFieldConfigId\030\001 \001(\005\022\017\n\007colName\030\002 \001(" +
      "\t\022\017\n\007colType\030\003 \001(\t\022\020\n\010colValue\030\004 \001(\t\022\016\n\006" +
      "action\030\005 \001(\t\022\022\n\ntargetType\030\006 \001(\t\022\022\n\ntarg" +
      "etName\030\007 \001(\t\022\024\n\014targetObject\030\010 \001(\t\022\020\n\010ta" +
      "rgetPk\030\t \001(\t\022\024\n\014targetPkType\030\n \001(\t\022\014\n\004ti" +
      "me\030\013 \001(\t\022\023\n\013mapperLogic\030\014 \001(\t\022\024\n\014targetD" +
      "bType\030\r \001(\tB\036\n\016mapper.controlB\014ProtobufD" +
      "ata"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pkg_QData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pkg_QData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pkg_QData_descriptor,
              new java.lang.String[] { "MapperFieldConfigId", "ColName", "ColType", "ColValue", "Action", "TargetType", "TargetName", "TargetObject", "TargetPk", "TargetPkType", "Time", "MapperLogic", "TargetDbType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
